(ns project-euler.p002
  (:require [project-euler.utils :refer [lazy-fibonacci]]))

;;; Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
;;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;;; By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

(defn sum-of-even-fib-values-less-than-n [n] (reduce +' (filter even? (take-while (partial > n) lazy-fibonacci))))

(defn solve [] (sum-of-even-fib-values-less-than-n 4000000))
